function buildCraneSimscapeModel()
%BUILDCRANESIMSCAPEMODEL Generate the Simscape Multibody crane model.

p = craneParameters();
setupCraneController();
root = fileparts(fileparts(mfilename("fullpath")));
modelDir = fullfile(root, "models");
if ~isfolder(modelDir)
    mkdir(modelDir);
end

mdl = char(p.modelName);
modelFile = fullfile(modelDir, mdl + ".slx");
if bdIsLoaded(mdl)
    close_system(mdl, 0);
end
if isfile(modelFile)
    delete(modelFile);
end

load_system("simulink");
load_system("sflib");
load_system("sm_lib");
load_system("nesl_utility");

new_system(mdl);
open_system(mdl);
set_param(mdl, ...
    "StopTime", num2str(p.stopTime), ...
    "SolverType", "Variable-step", ...
    "Solver", "ode23t");

% Library paths with embedded newlines, matching Simscape Multibody names.
worldPath = ['sm_lib/Frames and' newline 'Transforms/World Frame'];
mechPath = ['sm_lib/Utilities/Mechanism' newline 'Configuration'];
solverPath = "nesl_utility/Solver Configuration";
prisPath = ['sm_lib/Joints/Prismatic' newline 'Joint'];
revPath = "sm_lib/Joints/Revolute Joint";
brickPath = "sm_lib/Body Elements/Brick Solid";
spherePath = "sm_lib/Body Elements/Spherical Solid";
cylinderPath = "sm_lib/Body Elements/Cylindrical Solid";
rtPath = ['sm_lib/Frames and' newline 'Transforms/Rigid' newline 'Transform'];
tsPath = ['sm_lib/Frames and' newline 'Transforms/Transform' newline 'Sensor'];
contactPath = ['sm_lib/Forces and' newline 'Torques/Spatial' newline 'Contact Force'];
pointPath = "sm_lib/Curves and Surfaces/Point";
surfacePath = "sm_lib/Curves and Surfaces/Grid Surface";
psToSlPath = ['nesl_utility/PS-Simulink' newline 'Converter'];
slToPsPath = ['nesl_utility/Simulink-PS' newline 'Converter'];

% Visible pump/LQR controller path. Mode logic is Stateflow; the force law
% is a MATLAB Function block using parameters loaded from a MAT-file.
add_block("simulink/Sources/Clock", mdl + "/Clock", ...
    "Position", [30 25 80 55]);
add_block("sflib/Chart", mdl + "/Mode Logic", ...
    "Position", [150 25 300 180]);
configureModeLogicChart(mdl + "/Mode Logic");
add_block(['simulink/User-Defined' newline 'Functions/MATLAB Function'], ...
    mdl + "/Controller Force Law", ...
    "Position", [350 55 500 150]);
configureControllerForceLaw(mdl + "/Controller Force Law");
add_block("simulink/Discontinuities/Saturation", mdl + "/Force Saturation", ...
    "UpperLimit", num2str(p.forceMax), "LowerLimit", num2str(-p.forceMax), ...
    "Position", [540 60 630 95]);
add_block(slToPsPath, mdl + "/Force Converter", ...
    "Unit", "N", "Position", [670 55 770 105]);
add_block("simulink/Sinks/To Workspace", mdl + "/mode", ...
    "VariableName", "mode", "SaveFormat", "Timeseries", ...
    "Position", [350 180 440 210]);

% Multibody plant blocks.
add_block(worldPath, mdl + "/World Frame", "Position", [70 240 145 285]);
add_block(mechPath, mdl + "/Mechanism Configuration", ...
    "GravityVector", sprintf("[0 -%g 0]", p.gravity), ...
    "Position", [70 310 165 355]);
add_block(solverPath, mdl + "/Solver Configuration", "Position", [70 380 165 425]);

% Simscape Multibody prismatic primitives translate along their local Z
% axis. Rotate the joint frames so the prismatic Z axis is global X, then
% rotate back to a world-aligned trolley frame for the pendulum.
add_block(rtPath, mdl + "/Travel Axis Transform", ...
    "RotationMethod", "StandardAxis", ...
    "RotationStandardAxis", "+Y", ...
    "RotationAngle", "90", ...
    "RotationAngleUnits", "deg", ...
    "Position", [170 250 240 320]);
add_block(rtPath, mdl + "/Trolley Frame Transform", ...
    "RotationMethod", "StandardAxis", ...
    "RotationStandardAxis", "+Y", ...
    "RotationAngle", "-90", ...
    "RotationAngleUnits", "deg", ...
    "Position", [410 250 470 320]);

add_block(prisPath, mdl + "/Trolley Prismatic Joint", ...
    "TorqueActuationMode", "Input", ...
    "SensePosition", "on", "SenseVelocity", "on", "SenseTorqueForce", "on", ...
    "Position", [250 250 390 330]);

add_block(brickPath, mdl + "/Trolley Solid", ...
    "BrickDimensions", mat2str(p.trolleySize), ...
    "BrickDimensionsUnits", "m", ...
    "InertiaType", "Custom", ...
    "Mass", num2str(p.trolleyMass), "MassUnits", "kg", ...
    "GraphicType", "FromGeometry", ...
    "GraphicVisPropType", "SimpleVisualProperties", ...
    "GraphicDiffuseColor", "[0.0 0.45 0.74]", ...
    "Position", [480 250 610 320]);

add_block(rtPath, mdl + "/Pendulum Offset", ...
    "TranslationMethod", "Cartesian", ...
    "TranslationCartesianOffset", sprintf("[0 -%g 0]", p.pendulumLength), ...
    "TranslationCartesianOffsetUnits", "m", ...
    "Position", [700 255 820 325]);
add_block(rtPath, mdl + "/Cable Visual Offset", ...
    "TranslationMethod", "Cartesian", ...
    "TranslationCartesianOffset", sprintf("[0 -%g 0]", p.pendulumLength/2), ...
    "TranslationCartesianOffsetUnits", "m", ...
    "RotationMethod", "StandardAxis", ...
    "RotationStandardAxis", "+X", ...
    "RotationAngle", "90", ...
    "RotationAngleUnits", "deg", ...
    "Position", [700 500 820 570]);
add_block(cylinderPath, mdl + "/Cable Visual", ...
    "CylinderRadius", "0.015", ...
    "CylinderRadiusUnits", "m", ...
    "CylinderLength", num2str(p.pendulumLength), ...
    "CylinderLengthUnits", "m", ...
    "InertiaType", "Custom", ...
    "Mass", "0", "MassUnits", "kg", ...
    "MomentsOfInertia", "[0 0 0]", ...
    "MomentsOfInertiaUnits", "kg*m^2", ...
    "ProductsOfInertia", "[0 0 0]", ...
    "ProductsOfInertiaUnits", "kg*m^2", ...
    "GraphicType", "FromGeometry", ...
    "GraphicVisPropType", "SimpleVisualProperties", ...
    "GraphicDiffuseColor", "[0.08 0.08 0.08]", ...
    "Position", [900 500 1030 570]);
add_block(revPath, mdl + "/Pendulum Revolute Joint", ...
    "PositionTargetSpecify", "on", ...
    "PositionTargetValue", "0", ...
    "PositionTargetValueUnits", "deg", ...
    "SensePosition", "on", "SenseVelocity", "on", ...
    "Position", [630 370 780 450]);
add_block(spherePath, mdl + "/Payload Solid", ...
    "SphereRadius", num2str(p.payloadRadius), "SphereRadiusUnits", "m", ...
    "InertiaType", "Custom", ...
    "Mass", num2str(p.payloadMass), "MassUnits", "kg", ...
    "GraphicType", "FromGeometry", ...
    "GraphicVisPropType", "SimpleVisualProperties", ...
    "GraphicDiffuseColor", "[0.85 0.33 0.10]", ...
    "Position", [900 365 1030 435]);

% Visual rail and wall plus contact frame.
add_block(brickPath, mdl + "/Rail Visual", ...
    "BrickDimensions", mat2str(p.railSize), ...
    "BrickDimensionsUnits", "m", ...
    "InertiaType", "Custom", "Mass", "1", "MassUnits", "kg", ...
    "GraphicType", "FromGeometry", ...
    "GraphicVisPropType", "SimpleVisualProperties", ...
    "GraphicDiffuseColor", "[0.35 0.35 0.35]", ...
    "Position", [300 500 430 570]);
add_block(rtPath, mdl + "/Rail Offset", ...
    "TranslationMethod", "Cartesian", ...
    "TranslationCartesianOffset", "[0 0 0]", ...
    "TranslationCartesianOffsetUnits", "m", ...
    "Position", [170 510 270 560]);

add_block(brickPath, mdl + "/Wall Solid", ...
    "BrickDimensions", mat2str([p.wallWidth p.wallHeight p.wallThickness]), ...
    "BrickDimensionsUnits", "m", ...
    "InertiaType", "Custom", "Mass", "50", "MassUnits", "kg", ...
    "GraphicType", "FromGeometry", ...
    "GraphicVisPropType", "SimpleVisualProperties", ...
    "GraphicDiffuseColor", "[0.64 0.16 0.16]", ...
    "Position", [300 635 430 705]);
add_block(rtPath, mdl + "/Wall Offset", ...
    "TranslationMethod", "Cartesian", ...
    "TranslationCartesianOffset", mat2str([p.wallX p.wallBaseY + p.wallHeight/2 0]), ...
    "TranslationCartesianOffsetUnits", "m", ...
    "Position", [170 645 270 695]);
add_block(rtPath, mdl + "/Wall Plane Orient", ...
    "RotationMethod", "StandardAxis", ...
    "RotationStandardAxis", "+Y", ...
    "RotationAngle", "-90", ...
    "RotationAngleUnits", "deg", ...
    "Position", [760 630 860 700]);

add_block(contactPath, mdl + "/Payload Wall Contact", ...
    "NormalStiffness", num2str(p.contactStiffness), ...
    "NormalDamping", num2str(p.contactDamping), ...
    "NormalTransitionRegionWidth", num2str(p.contactTransition), ...
    "SenseContactSignal", "on", ...
    "SenseNormalForceMagnitude", "on", ...
    "Position", [1080 520 1230 600]);
add_block(pointPath, mdl + "/Payload Contact Point", ...
    "Position", [900 510 1030 570]);
add_block(surfacePath, mdl + "/Wall Contact Surface", ...
    "XGridVector", mat2str([-p.wallWidth/2 p.wallWidth/2]), ...
    "XGridVectorUnits", "m", ...
    "YGridVector", mat2str([-p.wallHeight/2 p.wallHeight/2]), ...
    "YGridVectorUnits", "m", ...
    "ZHeights", "[0 0; 0 0]", ...
    "ZHeightsUnits", "m", ...
    "Position", [900 630 1030 700]);

% Sensors.
add_block(tsPath, mdl + "/Payload Transform Sensor", ...
    "SenseX", "on", "SenseY", "on", ...
    "Position", [1080 250 1230 335]);

sensorNames = ["xTrolley" "vTrolley" "theta" "omega" "yBob" "xBob" "contactFlag" "contactForce"];
units = ["m" "m/s" "rad" "rad/s" "m" "m" "1" "N"];
for k = 1:numel(sensorNames)
    y = 90 + 45*k;
    add_block(psToSlPath, mdl + "/" + sensorNames(k) + " Converter", ...
        "Unit", units(k), "Position", [1290 y 1385 y+28]);
    add_block("simulink/Sinks/To Workspace", mdl + "/" + sensorNames(k), ...
        "VariableName", sensorNames(k), "SaveFormat", "Timeseries", ...
        "Position", [1435 y 1535 y+28]);
end

% Lines.
add_line(mdl, "Mode Logic/1", "Controller Force Law/1", "autorouting", "on");
add_line(mdl, "Mode Logic/1", "mode/1", "autorouting", "on");
add_line(mdl, "Clock/1", "Mode Logic/1", "autorouting", "on");
add_line(mdl, "Clock/1", "Controller Force Law/2", "autorouting", "on");
add_line(mdl, "Controller Force Law/1", "Force Saturation/1", "autorouting", "on");
add_line(mdl, "Force Saturation/1", "Force Converter/1", "autorouting", "on");

connectByPort(mdl, "Force Converter", "RConn1", "Trolley Prismatic Joint", "LConn2");
connectByPort(mdl, "World Frame", "RConn1", "Mechanism Configuration", "RConn1");
connectByPort(mdl, "World Frame", "RConn1", "Solver Configuration", "RConn1");
connectByPort(mdl, "World Frame", "RConn1", "Travel Axis Transform", "LConn1");
connectByPort(mdl, "Travel Axis Transform", "RConn1", "Trolley Prismatic Joint", "LConn1");
connectByPort(mdl, "Trolley Prismatic Joint", "RConn1", "Trolley Frame Transform", "LConn1");
connectByPort(mdl, "Trolley Frame Transform", "RConn1", "Trolley Solid", "RConn1");
connectByPort(mdl, "Trolley Frame Transform", "RConn1", "Pendulum Revolute Joint", "LConn1");
connectByPort(mdl, "Pendulum Revolute Joint", "RConn1", "Pendulum Offset", "LConn1");
connectByPort(mdl, "Pendulum Offset", "RConn1", "Payload Solid", "RConn1");
connectByPort(mdl, "Pendulum Revolute Joint", "RConn1", "Cable Visual Offset", "LConn1");
connectByPort(mdl, "Cable Visual Offset", "RConn1", "Cable Visual", "RConn1");
connectByPort(mdl, "World Frame", "RConn1", "Rail Offset", "LConn1");
connectByPort(mdl, "Rail Offset", "RConn1", "Rail Visual", "RConn1");
connectByPort(mdl, "World Frame", "RConn1", "Wall Offset", "LConn1");
connectByPort(mdl, "Wall Offset", "RConn1", "Wall Solid", "RConn1");
connectByPort(mdl, "Payload Solid", "RConn1", "Payload Contact Point", "LConn1");
connectByPort(mdl, "Payload Contact Point", "RConn1", "Payload Wall Contact", "LConn1");
connectByPort(mdl, "Wall Offset", "RConn1", "Wall Plane Orient", "LConn1");
connectByPort(mdl, "Wall Plane Orient", "RConn1", "Wall Contact Surface", "LConn1");
connectByPort(mdl, "Wall Contact Surface", "RConn1", "Payload Wall Contact", "RConn1");
connectByPort(mdl, "World Frame", "RConn1", "Payload Transform Sensor", "LConn1");
connectByPort(mdl, "Payload Solid", "RConn1", "Payload Transform Sensor", "RConn1");

connectByPort(mdl, "Trolley Prismatic Joint", "RConn2", "xTrolley Converter", "LConn1");
connectByPort(mdl, "Trolley Prismatic Joint", "RConn3", "vTrolley Converter", "LConn1");
connectByPort(mdl, "Pendulum Revolute Joint", "RConn2", "theta Converter", "LConn1");
connectByPort(mdl, "Pendulum Revolute Joint", "RConn3", "omega Converter", "LConn1");
connectByPort(mdl, "Payload Transform Sensor", "RConn2", "xBob Converter", "LConn1");
connectByPort(mdl, "Payload Transform Sensor", "RConn3", "yBob Converter", "LConn1");
connectByPort(mdl, "Payload Wall Contact", "RConn2", "contactFlag Converter", "LConn1");
connectByPort(mdl, "Payload Wall Contact", "RConn3", "contactForce Converter", "LConn1");

for k = 1:numel(sensorNames)
    add_line(mdl, sensorNames(k) + " Converter/1", sensorNames(k) + "/1", "autorouting", "on");
end
add_line(mdl, "xBob Converter/1", "Mode Logic/2", "autorouting", "on");
add_line(mdl, "yBob Converter/1", "Mode Logic/3", "autorouting", "on");
add_line(mdl, "vTrolley Converter/1", "Mode Logic/4", "autorouting", "on");
add_line(mdl, "theta Converter/1", "Mode Logic/5", "autorouting", "on");
add_line(mdl, "omega Converter/1", "Mode Logic/6", "autorouting", "on");
add_line(mdl, "xTrolley Converter/1", "Controller Force Law/3", "autorouting", "on");
add_line(mdl, "vTrolley Converter/1", "Controller Force Law/4", "autorouting", "on");
add_line(mdl, "theta Converter/1", "Controller Force Law/5", "autorouting", "on");
add_line(mdl, "omega Converter/1", "Controller Force Law/6", "autorouting", "on");

Simulink.BlockDiagram.arrangeSystem(mdl);
save_system(mdl, modelFile);
fprintf("Generated %s\n", modelFile);
end

function configureModeLogicChart(blockPath)
rt = sfroot;
chart = rt.find("-isa", "Stateflow.Chart", "Path", char(blockPath));
chart.ActionLanguage = "MATLAB";

inputNames = ["t", "xBob", "yBob", "vTrolley", "theta", "omega"];
for k = 1:numel(inputNames)
    d = Stateflow.Data(chart);
    d.Name = char(inputNames(k));
    d.Scope = "Input";
    d.Port = k;
end

d = Stateflow.Data(chart);
d.Name = "mode";
d.Scope = "Output";
d.Port = 1;

parameterNames = ["ctrl_wallX", "ctrl_wallTop", "ctrl_transferClearance", ...
    "ctrl_pendulumLength"];
for k = 1:numel(parameterNames)
    d = Stateflow.Data(chart);
    d.Name = char(parameterNames(k));
    d.Scope = "Parameter";
end

pump = Stateflow.State(chart);
pump.Name = "Pump";
pump.Position = [40 60 120 70];
pump.LabelString = "Pump" + newline + "du: mode = 1;";

transfer = Stateflow.State(chart);
transfer.Name = "Transfer";
transfer.Position = [220 60 120 70];
transfer.LabelString = "Transfer" + newline + "du: mode = 2;";

postClear = Stateflow.State(chart);
postClear.Name = "PostClear";
postClear.Position = [400 60 120 70];
postClear.LabelString = "PostClear" + newline + "du: mode = 3;";

lqrCatch = Stateflow.State(chart);
lqrCatch.Name = "LQRCatch";
lqrCatch.Position = [580 60 120 70];
lqrCatch.LabelString = "LQRCatch" + newline + "du: mode = 4;";

defaultTransition = Stateflow.Transition(chart);
defaultTransition.Destination = pump;
defaultTransition.DestinationOClock = 0;
defaultTransition.SourceEndpoint = pump.Position(1:2) - [30 20];

t = Stateflow.Transition(chart);
t.Source = pump;
t.Destination = transfer;
t.LabelString = "[" + ...
    "t > 1 && " + ...
    "yBob > ctrl_wallTop + ctrl_transferClearance && " + ...
    "xBob < ctrl_wallX && " + ...
    "(vTrolley + ctrl_pendulumLength*cos(atan2(sin(theta),cos(theta)))*omega) > 0" + ...
    "]";

t = Stateflow.Transition(chart);
t.Source = transfer;
t.Destination = postClear;
t.LabelString = "[xBob > ctrl_wallX + 0.35]";

t = Stateflow.Transition(chart);
t.Source = postClear;
t.Destination = lqrCatch;
t.LabelString = "[abs(atan2(sin(theta),cos(theta))) < 0.9 && abs(omega) < 2.5]";
end

function configureControllerForceLaw(blockPath)
rt = sfroot;
chart = rt.find("-isa", "Stateflow.EMChart", "Path", char(blockPath));
scriptLines = [
    "function force = controllerForceLaw(mode,t,xTrolley,vTrolley,theta,omega)"
    "%#codegen"
    "thetaWrapped = atan2(sin(theta), cos(theta));"
    "xBob = xTrolley + ctrl_pendulumLength * sin(thetaWrapped);"
    "yBob = -ctrl_pendulumLength * cos(thetaWrapped);"
    "envelopeTime = min(t, ctrl_pumpControlDuration);"
    "envelope = sin(pi * envelopeTime / ctrl_pumpControlDuration)^2;"
    "pumpForce = ctrl_pumpControlAmplitude * envelope * sin(ctrl_pumpFrequency * t + ctrl_pumpControlPhase);"
    "centerForce = -ctrl_centerGain * xTrolley - ctrl_centerDamping * vTrolley;"
    "if mode == 1"
    "    if xBob > ctrl_wallX - 0.70 && yBob < ctrl_wallTop + ctrl_clearanceMargin"
    "        force = -ctrl_forceMax;"
    "    else"
    "        force = pumpForce + centerForce;"
    "    end"
    "elseif mode == 2"
    "    force = ctrl_transferForce - ctrl_transferDamping * vTrolley;"
    "elseif mode == 3"
    "    if xBob < ctrl_wallX + 0.80 && yBob < ctrl_wallTop + ctrl_clearanceMargin"
    "        force = ctrl_transferForce - ctrl_transferDamping * vTrolley;"
    "    else"
    "        force = -ctrl_postClearGain * (xTrolley - ctrl_targetX) - ctrl_postClearDamping * vTrolley;"
    "    end"
    "else"
    "    if xBob < ctrl_wallX + 0.80 && yBob < ctrl_wallTop + ctrl_clearanceMargin"
    "        force = ctrl_transferForce - ctrl_transferDamping * vTrolley;"
    "    else"
    "        x = [xTrolley - ctrl_targetX; vTrolley; thetaWrapped; omega];"
    "        force = ctrl_lqrScale * ctrl_K * x;"
    "    end"
    "end"
    "force = min(max(force, -ctrl_forceMax), ctrl_forceMax);"
    "end"
    ];
chart.Script = char(strjoin(scriptLines, newline));

parameterNames = ["ctrl_K", "ctrl_forceMax", "ctrl_pendulumLength", ...
    "ctrl_wallX", "ctrl_wallTop", "ctrl_clearanceMargin", ...
    "ctrl_pumpControlAmplitude", "ctrl_pumpControlDuration", ...
    "ctrl_pumpControlPhase", "ctrl_pumpFrequency", "ctrl_centerGain", ...
    "ctrl_centerDamping", "ctrl_transferForce", "ctrl_transferDamping", ...
    "ctrl_postClearGain", "ctrl_postClearDamping", "ctrl_targetX", ...
    "ctrl_lqrScale"];
for k = 1:numel(parameterNames)
    d = Stateflow.Data(chart);
    d.Name = char(parameterNames(k));
    d.Scope = "Parameter";
end
end

function connectByPort(mdl, srcBlock, srcType, dstBlock, dstType)
src = portHandle(mdl, srcBlock, srcType);
dst = portHandle(mdl, dstBlock, dstType);
add_line(mdl, src, dst, "autorouting", "on");
end

function h = portHandle(mdl, blockName, portType)
pc = get_param(mdl + "/" + blockName, "PortConnectivity");
idx = find(strcmp({pc.Type}, portType), 1);
if isempty(idx)
    error("Port %s not found on block %s.", portType, blockName);
end
handles = get_param(mdl + "/" + blockName, "PortHandles");
if startsWith(portType, "LConn")
    portNumber = sscanf(portType, "LConn%d");
    h = handles.LConn(portNumber);
elseif startsWith(portType, "RConn")
    portNumber = sscanf(portType, "RConn%d");
    h = handles.RConn(portNumber);
else
    error("Unsupported port type %s.", portType);
end
end
